version: "3.7"
services:

  postgres-db:
    image: postgres:13.1-alpine
    environment:
      - POSTGRES_USER=user-service
      - POSTGRES_PASSWORD=user-service
      - POSTGRES_DB=user_service
    ports:
      - "5432:5432"