version: "3.7"
services:

  postgres-db:
    image: postgres:13.1-alpine
    environment:
      - POSTGRES_USER=service-template
      - POSTGRES_PASSWORD=service-template
      - POSTGRES_DB=service_template
    ports:
      - "5432:5432"